### ISSUE TITLE
Check Ansible version meets minimum version requirement

### ISSUE THREAD

**Issue by StephenSeltzer** [selesy/workstation#125]
The could be done in either the playbook or in the workstation.sh script.
## Playbook
Pro:
- Easy to implement
- Easy to maintain (just another version variable)

Con:
- Cannot automatically update the version

## workstaion.sh
Pro:
- Can attempt to automatically update the version of Ansible

Con:
- More complex to implement. Cannot use simple numeric comparison due to 3 digit versioning scheme.
- It may not be desirable to automatically update the version due to other uses of Ansible on the developer machine. Could cause difficult to identify issues for the developer.

**Comment by smoyer64** [comment]
Resolved in 50c94bafe6305c211c8493e9fef4d8d6a9ffb1a4
