### ISSUE TITLE
Install `tfswitch` (and remove the versioned Terraform installation)

### ISSUE THREAD

**Issue by smoyer64** [selesy/workstation#349]
See https://tfswitch.warrensbox.com/.

**Comment by smoyer64** [comment]
Obsoleted by #350

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
