### ISSUE TITLE
Install versioned tools via `asdf`

### ISSUE THREAD

**Issue by smoyer64** [selesy/workstation#350]
As they provide a clean way to manage the tool versions being used on a project-by-project basis with a global fallback.  This also deprecates the original way of installing these tools, so the original method of installing each tool should be removed.

The tools to manage via `asdf` should be:

- [x] 1password-cli
- [ ] ansible
- [x] ant
- [ ] argocd
- [ ] asciidoctorj
- [x] awscli
- [ ] aws-iam-authenticator
- [x] aws-vault
- [ ] azure-cli
- [x] bazel
- [x] direnv
- [ ] docker-compose-v1
- [ ] flux2
- [ ] fluxctl
- [ ] fzf
- [ ] git
- [x] github-cli
- [x] golang
- [x] golangci-lint
- [x] gradle
- [x] grpcurl
- [x] helm
- [ ] istioctl
- [x] java
- [ ] jmeter
- [x] jq
- [x] k6
- [x] k9s
- [x] kind
- [x] ko
- [x] krew
- [x] kubectl
- [x] kubectx
- [x] kubeseal
- [x] kustomize
- [ ] linkerd
- [x] make
- [x] maven
- [x] minikube
- [x] nancy
- [x] nodejs
- [x] protoc-gen-go
- [x] protoc-gen-go-grpc
- [x] semver
- [x] skaffold
- [x] sops
- [ ] stripe-cli
- [x] swag
- [x] terraform
- [x] terragrunt
- [ ] vim
- [x] yq

See https://github.com/asdf-vm/asdf and run the following command to see the list of available plugins:

```
asdf plugin list all
```

New tools:
- [ ] hugo (TODO: pick one of the two plugins)

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.

**Comment by smoyer64** [comment]
Most tools should be versioned per-project rather than installed globally.
