### ISSUE TITLE
Update fails on common : upgrade existing apt packages

### ISSUE THREAD

**Issue by StephenSeltzer** [selesy/workstation#42]
When attempting to run workstation to update existing applications, the following error is produced. 

`TASK [common : upgrade existing apt packages] **************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "'/usr/bin/aptitude safe-upgrade' failed: Unable to safely resolve dependencies, try running with --full-resolver.\n", "rc": 255, "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\nBuilding tag database...\nResolving dependencies...\nUnable to resolve dependencies for the upgrade: no solution found.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Reading extended state information...", "Initializing package states...", "Building tag database...", "Resolving dependencies...", "Unable to resolve dependencies for the upgrade: no solution found."]}
	to retry, use: --limit @/home/stephen/git/workstation/workstation.retry
`
Was able to workaround by removing the "upgrade existing apt packages" task from roles/common/tasks/main.yml

**Comment by smoyer64** [comment]
This looks like a corrupt package download - does the following command work if you run it manually from the command line?

```
sudo apt-get update
```

**Comment by StephenSeltzer** [comment]
Yes, it does. I did a little research initially and found ansible uses aptitude and that there are sometime some issues with it.

**Comment by smoyer64** [comment]
Hmm ... I always use aptitude from the command line as:

```
sudo aptitude update
```

**Comment by StephenSeltzer** [comment]
I am able to run aptitude from the command line but workstation still fails.

**Comment by StephenSeltzer** [comment]
Re-ran aptitude manually with --full-resolver. Appears to have fixed the issues.
